<?php
/* Textos comunes en inglés: cabecera, pie, botones y avisos de seguridad. */
return array(
	'saltar'          => 'Skip to content',
	'inicio'          => 'Home',
	'migas'           => 'You are here',
	'menu_abrir'      => 'Open menu',
	'menu_cerrar'     => 'Close menu',
	'menu'            => array(
		'usos'      => 'Uses',
		'empresas'  => 'Business',
		'envios'    => 'Delivery',
		'contacto'  => 'Contact',
	),
	'usos'            => array(
		array( 'hosteleria', 'Hospitality', 'Smoke at the table, cocktails and cold behind the bar', 'uso-hosteleria' ),
		array( 'transporte', 'Cold-chain transport', 'Frozen and chilled goods on the road', 'uso-transporte' ),
		array( 'industria', 'Industry', 'Cooling parts, testing and bulk orders', 'uso-industria' ),
		array( 'laboratorios', 'Laboratories', 'Samples at −78.5 °C', 'uso-laboratorio' ),
		array( 'eventos', 'Parties and events', 'Low-lying fog and effects', 'uso-eventos' ),
	),
	'todos_usos'      => 'All uses of dry ice',
	'comprar'         => 'Buy dry ice',
	'comprar_corto'   => 'Buy',
	'llamar'          => 'Call',
	'carrito'         => 'Basket',
	'pago_seguro'     => 'Secure payment',
	'finalizar'       => 'Checkout',
	'no_encontrada'   => 'Page not found',
	'error404'        => array(
		'titulo'  => 'This page has <em>sublimated.</em>',
		'texto'   => 'It doesn’t exist or it has moved. This is what people usually look for:',
		'enlaces' => array( array( 'inicio', 'Home' ), array( 'envios', 'Delivery times and costs' ), array( 'empresas', 'Business account' ), array( 'contacto', 'Contact' ) ),
	),
	'wa_mensaje'      => 'Hello, I need dry ice. It’s for:',
	'wa_etiqueta'     => 'WhatsApp',
	'wa_aria'         => 'Message us on WhatsApp: +34 686 980 471',
	'idioma'          => 'Language',
	// Pie
	'pie_frase'       => 'Dry ice that arrives <em>cold</em> and on time.',
	'pie_tienda'      => 'Dry ice',
	'pie_servicio'    => 'Service',
	'pie_contacto'    => 'Let’s talk',
	'pie_enlaces'     => array(
		array( 'producto', 'Buy' ),
		array( 'que-es', 'What is dry ice' ),
		array( 'seguridad', 'Safety and data sheet' ),
		array( 'aplicaciones', 'Uses by sector' ),
		array( 'guias', 'Guides' ),
	),
	'pie_servicios'   => array(
		array( 'empresas', 'Business account' ),
		array( 'envios', 'Delivery times and costs' ),
		array( 'envios', 'Collection in Mataró', 'recogida' ),
		array( 'zonas', 'Delivery areas' ),
		array( 'contacto', 'Contact' ),
	),
	'horario'         => 'Monday to Friday, 9:00–18:00',
	'legales'         => array(
		array( 'aviso-legal', 'Legal notice' ),
		array( 'privacidad', 'Privacy' ),
		array( 'cookies', 'Cookies' ),
		array( 'condiciones', 'Terms of sale' ),
	),
	'config_cookies'  => 'Cookie settings',
	'derechos'        => 'DryIcePack is a brand of INDUNOVA IMS S.L. · CIF B66800103',
	// Entrega (reloj del corte)
	'corte_antes'     => 'Order before 12:00 for delivery on the morning of %s',
	'corte_quedan'    => '%s left until today’s cutoff',
	'corte_despues'   => 'Order now for delivery on the morning of %s',
	'horas'           => 'h',
	'minutos'         => 'min',
	// Seguridad: los seis avisos (se enlazan desde cualquier página que explica un uso)
	'seguridad'       => array(
		array( 'guante', 'Gloves and tongs', 'Never let it touch your skin: at −78.5 °C it burns.' ),
		array( 'ventilar', 'Ventilated space', 'CO₂ displaces oxygen in enclosed spaces.' ),
		array( 'hermetico', 'Nothing airtight', 'As it sublimates, pressure builds and can burst the container.' ),
		array( 'no-beber', 'Never eat or drink it', 'No pellets in the glass: always use a double container.' ),
		array( 'nino', 'Away from children and pets', 'Keep it in its box, out of their reach.' ),
		array( 'coche', 'In the boot', 'With ventilation. Never inside a closed car.' ),
	),
	'seguridad_mas'   => 'Full safety guide and data sheet',
	'faq'             => 'Frequently asked questions',
	'volver_arriba'   => 'Back to top',
	'ver_mas'         => 'See more',
	'kg'              => 'kg',
	'iva_incl'        => 'incl. VAT',
	'con_envio'       => 'incl. delivery',
	'por_kilo'        => '/kg',
	'form_privacidad' => 'I have read the <a href="%s">privacy policy</a>. We only use your details to reply to you.',
	'form_enviar'     => 'Send',
	'form_enviando'   => 'Sending…',
	'form_ok'         => 'Received. We reply during office hours, usually the same day.',
	'form_error'      => 'Your message could not be sent. Call us on +34 936 73 76 41.',
);
