<?php
/* Envíos y plazos · inglés */
return array(
	'menu' => 'Delivery times and costs',
	'seo'  => array(
		'titulo'      => 'Dry ice delivery in 24 h across mainland Spain | DryIcePack',
		'descripcion' => 'Dry ice delivery across mainland Spain: order before 12:00 and have it tomorrow morning. Work out your delivery cost here or collect it in Mataró.',
	),
	'migas'  => array( 'Home', 'Delivery times and costs' ),
	'hero'   => array(
		'titulo'   => 'Dry ice delivery:|<em>order today, have it tomorrow.</em>',
		'reloj'    => array( 'antes' => 'Time left to order today', 'despues' => 'Today’s order deadline has passed' ),
		'llega'    => array( 'antes' => 'Order now and you’ll have it on the morning of %s.', 'despues' => 'Order now and you’ll have it on the morning of %s.' ),
		'texto'    => 'Orders placed before 12:00 (Spanish time), Monday to Friday, leave the same day and arrive the next morning. You choose the day at checkout.',
	),
	'semana' => array(
		'titulo' => 'Which day will it arrive?|<em>It depends on when you order.</em>',
		'dias'   => array( 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday' ),
		'pides'  => 'You order before 12:00',
		'llega'  => 'Arrives',
		'filas'  => array(
			array( 0, 1, '' ),
			array( 1, 2, '' ),
			array( 2, 3, '' ),
			array( 3, 4, '' ),
			array( 4, 5, 'Saturday depending on area, +€11.74. Otherwise, Tuesday.' ),
		),
		'finde'  => 'Orders placed on Saturday or Sunday, or on Friday after 12:00, leave on Monday and arrive on Tuesday.',
		'festivos' => 'No orders leave on public holidays in Mataró, in Catalonia or across Spain, and there are no deliveries on the courier’s local holidays in your area. You don’t need to check: at checkout, you only see the days that are possible.',
	),
	'tarifa' => array(
		'titulo' => 'How much is delivery?|<em>Move the kilos and see.</em>',
		'kg'     => 'Kilos of ice',
		'mas'       => 'Over 150 kg',
		'mas_cifra' => '150+',
		'cajas_titulo' => 'How we pack it',
		'caja_una'     => '%1$s box of %2$s kg',
		'caja_varias'  => '%1$s boxes of %2$s kg',
		'caja_resto'   => ' + %1$s of %2$s kg',
		'pedir'     => array( 'boton' => 'Order %s kg', 'formato' => 'Format', 'f3mm' => '3 mm pellets', 'f16mm' => '16 mm nuggets', 'nota' => 'We put it in your basket exactly like this and take you to checkout.' ),
		'coste_iva' => 'Delivery, VAT included',
		'filas'     => array(
			'hielo'    => 'Ice',
			'embalaje' => 'Boxes (1 kg each)',
			'peso'     => 'Chargeable weight',
			'redondeo' => 'rounded up',
			'sin_iva'  => 'Delivery excl. VAT',
			'iva'      => 'VAT (%s)',
		),
		'tramo'  => 'rate up to %s kg',
		'extra'  => '%1$s up to 10 kg + %2$s kg × %3$s',
		'nota'   => 'We count 20 kg boxes and put the rest in the pack that covers it (3, 10 or 15 kg), as if you ordered it in the shop. The courier charges the ice plus 1 kg per box, rounded up: the same calculation as at checkout.',
		'medida' => array(
			'cajas'  => 'Boxes made up for your order',
			'titulo' => 'We’ll give you a price and a day.',
			'texto'  => 'In the province of Barcelona we bring it to your premises; elsewhere, delivery is arranged individually.',
			'boton'  => 'Ask for price',
			'wa'     => 'Hi, I need more than 150 kg of dry ice. Could you give me a price and a day?',
			'tel'    => 'or call',
		),
	),
	'recogida' => array(
		'titulo' => 'Collection in Mataró,|<em>no waiting in for the courier.</em>',
		'lista'  => array(
			array( 'Where', 'Camí Ca La Madrona 19 D, 08304 Mataró (Barcelona). It’s our own warehouse, not a courier depot.' ),
			array( 'When', 'Monday to Saturday, including public holidays. Choose the day at checkout and we confirm the time by phone or WhatsApp. Saturday has an €11.74 surcharge (VAT included).' ),
			array( 'Cost', 'Free Monday to Friday. You only pay for the ice, in cash on collection.' ),
			array( 'How to carry it', 'Never in the passenger compartment: in the boot, with ventilation.' ),
		),
		'alt'    => 'Worker with a scoop of dry ice pellets in the warehouse',
		'como'   => 'Get directions',
	),
	'cobertura' => array(
		'titulo' => 'Do you deliver to my area?',
		'si'     => array( 'titulo' => 'Yes, the next morning', 'texto' => 'All of mainland Spain: from Girona to Huelva and from A Coruña to Murcia.' ),
		'no'     => array( 'titulo' => 'Outside mainland Spain, no', 'texto' => 'We only deliver to mainland Spain: not to the Balearic or Canary Islands, Ceuta or Melilla, or outside Spain.' ),
		'zonas'  => 'See delivery areas near Barcelona',
	),
	'faq' => array(
		'titulo' => 'Delivery questions',
		'lista'  => array(
			array( 'How is it packed?', 'In an EPS box with 40 mm walls, closed with its lid but not airtight, so the CO₂ can escape during the journey.' ),
			array( 'Will the full weight I ordered arrive?', 'Dry ice sublimates from the moment it leaves the warehouse, so it loses some weight in transit. That’s why it leaves the day it’s packed and arrives the next morning: the shortest possible time on the road.' ),
			array( 'What if I’m not in when it arrives?', 'It’s best to give an address where someone will be in during the morning. If you’re still out, the courier makes its usual redelivery attempts: let us know as soon as possible so we can track the parcel, because the ice won’t wait.' ),
			array( 'Can I ask for a specific time?', 'Deliveries are in the morning and the exact time depends on the courier’s route. If you need to know the time, collect it in Mataró: we confirm it with you beforehand.' ),
			array( 'Do you offer same-day delivery?', 'Not by courier. If you’re near Mataró, you can collect it the same day if you order before 12:00. We confirm the time by phone or WhatsApp.' ),
		),
	),
);
