<?php
/* Comprar (ficha de producto) · inglés */
return array(
	'menu' => 'Buy dry ice',
	'seo'  => array(
		'titulo'      => 'Buy dry ice online: 3, 10, 15 and 20 kg | DryIcePack',
		'descripcion' => 'Buy dry ice from 3 kg, as 3 mm pellets or 16 mm nuggets. See the total with delivery before you pay. Order before 12:00 and it arrives tomorrow.',
	),
	'migas'   => array( 'Home', 'Buy dry ice' ),
	'titulo'  => 'Buy dry ice with no surprise delivery costs',
	'sub'     => 'Order before 12:00 and you’ll have it tomorrow morning (Tuesday to Saturday), or pick any day you like. The total already includes delivery.',
	'galeria' => array(
		'3mm'  => array( array( 'caja-3mm', 'Open box of 3 mm dry ice pellets, with vapour' ), array( 'cenital-3mm', 'Top view of 3 mm dry ice pellets' ), array( 'caja-3mm-lateral', 'EPS box of 3 mm pellets with the lid propped against it' ) ),
		'16mm' => array( array( 'caja-16mm-niebla', 'Open box of 16 mm dry ice nuggets, with vapour' ), array( 'cenital-16mm', 'Top view of 16 mm dry ice nuggets' ), array( 'cenital-caja-nuggets', 'Open EPS box of 16 mm nuggets, seen from above' ) ),
	),
	'formato' => 'Format',
	'formatos' => array(
		'3mm'  => array( '3 mm pellets', 'Cools faster. More fog.' ),
		'16mm' => array( '16 mm nuggets', 'Lasts longer. Transport and samples.' ),
	),
	'kilos'     => 'Kilos per box',
	'cajas'     => 'Boxes',
	'menos'     => 'Remove a box',
	'mas'       => 'Add a box',
	'cp'        => 'Your postcode',
	'cp_ph'     => '08301',
	// Line under the field: help and status (one short line)
	'cp_ayuda'     => 'To see which day it arrives',
	'cp_buscando'  => 'Finding your area…',
	'cp_correcto'  => 'Postcode OK',
	'cp_fuera'     => 'Outside mainland Spain',
	'cp_medida'    => 'Custom delivery',
	'cp_no_valido' => 'Postcode not valid',
	'cp_corto'     => 'Missing digits: 5 needed',
	// Delivery line with the postcode (%1$s = "08301 · Barcelona", %2$s = date); "medida" ends with a WhatsApp link; "fuera" doesn't (no delivery)
	'llega_cp_ok'     => '%1$s — arrives on the morning of %2$s',
	'llega_cp_sabado' => 'Or %1$s in some areas: +%2$s',
	'llega_cp_fuera'  => 'we only deliver to mainland Spain: not to the Balearic or Canary Islands, Ceuta or Melilla.',
	'llega_cp_medida' => 'over 150 kg outside the province of Barcelona: order via',
	'llega_cp_error'  => 'Postcode %s does not exist in Spain. Check the 5 digits.',
	'llega'     => 'You’ll have it on the morning of %s',
	'llega_hoy' => 'Order before 12:00 (Spanish time) and you’ll have it on the morning of %s',
	'fuera'     => 'We only deliver to mainland Spain: not to the Balearic or Canary Islands, Ceuta or Melilla.',
	'precio'    => 'Dry ice',
	'envio'     => 'Delivery',
	'total'     => 'Total',
	'iva'       => 'VAT included',
	'boton'     => 'Place my order',
	'recogida'  => 'Or collect it in Mataró: free Monday to Friday, and you pay in cash on collection.',
	'max'       => 'Up to 250 kg per order. Need more? Message us and we’ll give you a price and a day.',
	'medida'    => 'Over 150 kg outside the province of Barcelona: that delivery is arranged individually. Message us on',
	'confianza' => array( 'Card, Apple Pay or Google Pay', 'Invoices for businesses', 'No account needed' ),
	'caja' => array(
		'titulo' => 'How it arrives|<em>at your door.</em>',
		'capas'  => array(
			array( 'EPS lid', 'Fits without an airtight seal: the gas escapes little by little.' ),
			array( 'Dry ice', '3 mm pellets or 16 mm nuggets, at −78.5 °C.' ),
			array( '40 mm EPS box', 'Thick polystyrene walls: they insulate and make the ice last longer.' ),
		),
	),
	'comparar' => array(
		'titulo' => '3 mm or 16 mm?|<em>Drag</em> to compare.',
		'izq'    => array( '3 mm', 'More surface area: cools faster and makes more fog. For cocktails, effects and processes.' ),
		'der'    => array( '16 mm', 'More mass per piece: lasts longer in the box. For transport, samples and the cold chain.' ),
		'rango'  => 'Slide to compare 3 mm and 16 mm',
	),
	'cuanto' => array(
		'titulo' => 'How much|<em>do I need?</em>',
		'texto'  => 'For fog, use these quantities as a guide. Is it for transport or samples? Tell us how many hours and what volume, and we’ll work it out for you.',
		'casos'  => array(
			array( '3 kg', 'At home', 'A cauldron, a punch bowl with a double container, a small party.' ),
			array( '10 kg', 'Big party', 'Fog across the floor in several rounds through the night.' ),
			array( '15–20 kg', 'Bar or event', 'A long service, a stage or several bars.' ),
		),
		'calcula' => 'Ask us on WhatsApp',
		'seguridad' => 'Before you use it, read the six safety rules',
	),
	'tarifa' => array(
		'titulo' => 'What does|<em>delivery cost?</em>',
		'texto'  => 'The courier’s rate, the same across mainland Spain. It’s based on the weight of the ice plus 1 kg per box, and you see it before you pay.',
		'filas'  => array( array( 'Up to 2 kg', 8.53 ), array( 'Up to 5 kg', 10.32 ), array( 'Up to 10 kg', 13.19 ), array( 'Each extra kg', 1.12 ) ),
		'extra'  => array( array( 'Saturday delivery (depending on area)', 9.70 ), array( 'Collection in Mataró, Monday to Friday', 0 ) ),
		'nota'   => 'Prices include VAT.',
		'gratis' => 'Free',
		'enlace' => 'Delivery times, holidays and collection',
	),
	'faq' => array(
		'titulo'   => 'Before you pay',
		'empresas' => 'Business account with monthly invoicing',
		'lista'    => array(
			array( 'When will it arrive?', 'If you order before 12:00, Monday to Thursday, it leaves the same day and you have it the next morning. Order on Friday and it arrives on Saturday (depending on the area, with an €11.74 surcharge) or on Tuesday. We don’t deliver on Sunday or Monday. You choose the day at checkout.' ),
			array( 'Can I order for another day?', 'Yes: at checkout you can choose any day in the next 90 with delivery to your area, Tuesday to Saturday (Saturday depending on the area, with a surcharge). Order it for the day you’ll use it: dry ice sublimates over time.' ),
			array( 'How long does the ice last in the box?', 'It depends on the temperature and how often the box is opened. Order it for the day you’ll use it and keep it closed until then. If you need it for several days, message us and we’ll work it out.' ),
			array( 'What if I need an invoice?', 'If you’re an individual and the order is up to €400 (VAT included), the simplified invoice reaches you by email from info@dryicepack.es, without asking. If you’re buying for a company or as self-employed, tick the box at checkout and enter the company name and tax ID: you get the full invoice. If you forget, we’ll send you a link to request it.' ),
			array( 'Can I return it?', 'Dry ice sublimates from the moment it leaves us, so there is no right of withdrawal. If there’s a problem when it arrives, call us the same day.' ),
			array( 'How do I store it when it arrives?', 'With thermal gloves, never with bare hands. In its box, with the lid on but not taped shut, somewhere ventilated and out of reach of children and pets. Never in the freezer or an airtight container: the pressure can burst it. It must never be eaten or drunk. And if you take it by car, put it in the boot and keep the car ventilated.' ),
		),
	),
	'barra' => 'Total',
);
