<?php
/* Textos comunes en castellano: cabecera, pie, botones y avisos de seguridad. */
return array(
	'saltar'          => 'Saltar al contenido',
	'inicio'          => 'Inicio',
	'migas'           => 'Estás en',
	'menu_abrir'      => 'Abrir menú',
	'menu_cerrar'     => 'Cerrar menú',
	'menu'            => array(
		'usos'      => 'Usos',
		'empresas'  => 'Empresas',
		'envios'    => 'Envíos',
		'contacto'  => 'Contacto',
	),
	'usos'            => array(
		array( 'hosteleria', 'Hostelería', 'Humo en sala, cócteles y frío en barra', 'uso-hosteleria' ),
		array( 'transporte', 'Transporte en frío', 'Congelado y refrigerado en ruta', 'uso-transporte' ),
		array( 'industria', 'Industria', 'Enfriar piezas, ensayos y volumen', 'uso-industria' ),
		array( 'laboratorios', 'Laboratorios', 'Muestras a −78,5 °C', 'uso-laboratorio' ),
		array( 'eventos', 'Fiestas y eventos', 'Niebla baja y efectos', 'uso-eventos' ),
	),
	'todos_usos'      => 'Todos los usos del hielo seco',
	'comprar'         => 'Comprar hielo seco',
	'comprar_corto'   => 'Comprar',
	'llamar'          => 'Llamar',
	'carrito'         => 'Carrito',
	'pago_seguro'     => 'Pago seguro',
	'finalizar'       => 'Finalizar compra',
	'no_encontrada'   => 'Página no encontrada',
	'error404'        => array(
		'titulo'  => 'Esta página se ha <em>sublimado.</em>',
		'texto'   => 'No existe o ha cambiado de dirección. Esto es lo que suele buscarse:',
		'enlaces' => array( array( 'inicio', 'Inicio' ), array( 'envios', 'Envíos y plazos' ), array( 'empresas', 'Cuenta de empresa' ), array( 'contacto', 'Contacto' ) ),
	),
	'wa_mensaje'      => 'Hola, necesito hielo seco. Mi uso es:',
	'wa_etiqueta'     => 'WhatsApp',
	'wa_aria'         => 'Escríbenos por WhatsApp al 686 980 471',
	'idioma'          => 'Idioma',
	// Pie
	'pie_frase'       => 'Hielo seco que llega <em>frío</em> y a su hora.',
	'pie_tienda'      => 'Hielo seco',
	'pie_servicio'    => 'Servicio',
	'pie_contacto'    => 'Hablemos',
	'pie_enlaces'     => array(
		array( 'producto', 'Comprar' ),
		array( 'que-es', 'Qué es el hielo seco' ),
		array( 'seguridad', 'Seguridad y ficha técnica' ),
		array( 'aplicaciones', 'Usos por sector' ),
		array( 'guias', 'Guías' ),
	),
	'pie_servicios'   => array(
		array( 'empresas', 'Cuenta de empresa' ),
		array( 'envios', 'Envíos y plazos' ),
		array( 'envios', 'Recogida en Mataró', 'recogida' ),
		array( 'zonas', 'Zonas de entrega' ),
		array( 'contacto', 'Contacto' ),
	),
	'horario'         => 'Lunes a viernes, 9:00–18:00',
	'legales'         => array(
		array( 'aviso-legal', 'Aviso legal' ),
		array( 'privacidad', 'Privacidad' ),
		array( 'cookies', 'Cookies' ),
		array( 'condiciones', 'Condiciones de venta' ),
	),
	'config_cookies'  => 'Configurar cookies',
	'derechos'        => 'DryIcePack es una marca de INDUNOVA IMS S.L. · CIF B66800103',
	// Entrega (reloj del corte)
	'corte_antes'     => 'Pide antes de las 12:00 y llega el %s por la mañana',
	'corte_quedan'    => 'Quedan %s para el corte de hoy',
	'corte_despues'   => 'Si pides ahora, llega el %s por la mañana',
	'horas'           => 'h',
	'minutos'         => 'min',
	// Seguridad: los seis avisos (se enlazan desde cualquier página que explica un uso)
	'seguridad'       => array(
		array( 'guante', 'Guantes y pinzas', 'Nunca en contacto con la piel: a −78,5 °C quema.' ),
		array( 'ventilar', 'Espacio ventilado', 'El CO₂ desplaza el oxígeno en sitios cerrados.' ),
		array( 'hermetico', 'Nada hermético', 'Al sublimarse aumenta la presión y puede reventar el envase.' ),
		array( 'no-beber', 'No se come ni se bebe', 'Nunca pellets dentro de la copa: siempre doble recipiente.' ),
		array( 'nino', 'Lejos de niños y mascotas', 'Guárdalo en su caja, fuera de su alcance.' ),
		array( 'coche', 'En el maletero', 'Y con ventilación, nunca en el habitáculo cerrado.' ),
	),
	'seguridad_mas'   => 'Seguridad completa y ficha de datos',
	'faq'             => 'Preguntas frecuentes',
	'volver_arriba'   => 'Volver arriba',
	'ver_mas'         => 'Ver más',
	'kg'              => 'kg',
	'iva_incl'        => 'IVA incl.',
	'con_envio'       => 'con envío',
	'por_kilo'        => '/kg',
	'form_privacidad' => 'He leído la <a href="%s">política de privacidad</a>. Usamos tus datos solo para responderte.',
	'form_enviar'     => 'Enviar',
	'form_enviando'   => 'Enviando…',
	'form_ok'         => 'Recibido. Te respondemos en horario laboral, normalmente el mismo día.',
	'form_error'      => 'No se ha podido enviar. Llámanos al 936 73 76 41.',
);
