<?php
/* Envíos y plazos · castellano */
return array(
	'menu' => 'Envíos y plazos',
	'seo'  => array(
		'titulo'      => 'Envío de hielo seco en 24 h a toda la península | DryIcePack',
		'descripcion' => 'Envío de hielo seco a toda la península: pide antes de las 12:00 y mañana por la mañana lo tienes. Calcula aquí el envío o recógelo en Mataró.',
	),
	'migas'  => array( 'Inicio', 'Envíos y plazos' ),
	'hero'   => array(
		'titulo'   => 'Envío de hielo seco:|<em>pides hoy, mañana lo tienes.</em>',
		'reloj'    => array( 'antes' => 'Tiempo para pedir hoy', 'despues' => 'Por hoy ya ha pasado la hora límite' ),
		'llega'    => array( 'antes' => 'Si pides ahora, lo tienes el %s por la mañana.', 'despues' => 'Si pides ahora, lo tienes el %s por la mañana.' ),
		'texto'    => 'Lo que entra antes de las 12:00, de lunes a viernes, sale ese mismo día y llega al siguiente por la mañana. El día lo eliges al pagar.',
	),
	'semana' => array(
		'titulo' => '¿Qué día llega?|<em>Depende de cuándo pidas.</em>',
		'dias'   => array( 'Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado', 'Domingo' ),
		'pides'  => 'Pides antes de las 12:00',
		'llega'  => 'Llega',
		'filas'  => array(
			array( 0, 1, '' ),
			array( 1, 2, '' ),
			array( 2, 3, '' ),
			array( 3, 4, '' ),
			array( 4, 5, 'Sábado según zona, +11,74 €. Si no, el martes.' ),
		),
		'finde'  => 'Pedidos del sábado y el domingo, o del viernes después de las 12:00: salen el lunes y llegan el martes.',
		'festivos' => 'Si es festivo en Mataró, en Cataluña o en toda España, no salen pedidos, y tampoco se entrega en un festivo de la mensajería en tu zona. No tienes que mirarlo: al pagar solo aparecen los días posibles.',
	),
	'tarifa' => array(
		'titulo' => '¿Cuánto cuesta el envío?|<em>Mueve los kilos y lo ves.</em>',
		'kg'     => 'Kilos de hielo',
		'mas'       => 'Más de 150 kg',
		'mas_cifra' => '+150',
		'cajas_titulo' => 'Así te lo enviamos',
		'caja_una'     => '%1$s caja de %2$s kg',
		'caja_varias'  => '%1$s cajas de %2$s kg',
		'caja_resto'   => ' + %1$s de %2$s kg',
		'pedir'     => array( 'boton' => 'Pedir %s kg', 'formato' => 'Formato', 'f3mm' => 'Pellets 3 mm', 'f16mm' => 'Nuggets 16 mm', 'nota' => 'Te lo dejamos en el carrito tal cual y vas al pago.' ),
		'coste_iva' => 'Envío, IVA incluido',
		'filas'     => array(
			'hielo'    => 'Hielo',
			'embalaje' => 'Cajas (1 kg cada una)',
			'peso'     => 'Peso facturable',
			'redondeo' => 'redondeado al alza',
			'sin_iva'  => 'Envío sin IVA',
			'iva'      => 'IVA (%s)',
		),
		'tramo'  => 'tarifa hasta %s kg',
		'extra'  => '%1$s hasta 10 kg + %2$s kg × %3$s',
		'nota'   => 'Contamos cajas de 20 kg y el resto en el pack que toque (3, 10 o 15 kg), como si lo pidieras en la tienda. La mensajería cobra el hielo más 1 kg por caja, redondeado al alza: la misma cuenta que se hace al pagar.',
		'medida' => array(
			'cajas'  => 'Cajas a medida del pedido',
			'titulo' => 'Te preparamos precio y día.',
			'texto'  => 'En la provincia de Barcelona te lo llevamos a tus instalaciones; fuera, el envío va a medida.',
			'boton'  => 'Pedir precio',
			'wa'     => 'Hola, necesito más de 150 kg de hielo seco. ¿Me preparáis precio y día?',
			'tel'    => 'o llama al',
		),
	),
	'recogida' => array(
		'titulo' => 'Recogida en Mataró,|<em>sin esperar a la mensajería.</em>',
		'lista'  => array(
			array( 'Dónde', 'Camí Ca La Madrona 19 D, 08304 Mataró (Barcelona). Es nuestra nave, no una oficina de la mensajería.' ),
			array( 'Cuándo', 'De lunes a sábado, también festivos. Elige el día al pagar y te confirmamos la hora por teléfono o WhatsApp. El sábado tiene un suplemento de 11,74 € (IVA incluido).' ),
			array( 'Cuánto', 'Gratis de lunes a viernes. Pagas solo el hielo, en efectivo al recogerlo.' ),
			array( 'Cómo llevarlo', 'Nunca en el habitáculo: en el maletero y ventilando.' ),
		),
		'alt'    => 'Operario con un cazo de pellets de hielo seco en el almacén',
		'como'   => 'Cómo llegar',
	),
	'cobertura' => array(
		'titulo' => '¿Llega a mi zona?',
		'si'     => array( 'titulo' => 'Sí, al día siguiente por la mañana', 'texto' => 'Toda la España peninsular: de Girona a Huelva y de A Coruña a Murcia.' ),
		'no'     => array( 'titulo' => 'Fuera de la península, no', 'texto' => 'Solo enviamos a la península: no a Baleares, Canarias, Ceuta ni Melilla, ni fuera de España.' ),
		'zonas'  => 'Ver zonas de entrega cerca de Barcelona',
	),
	'faq' => array(
		'titulo' => 'Dudas de envío',
		'lista'  => array(
			array( '¿Cómo va embalado?', 'En caja de EPS de 40 mm de pared, cerrada con su tapa pero no hermética, para que el CO₂ pueda salir durante el viaje.' ),
			array( '¿Llega el mismo peso que pido?', 'El hielo seco se sublima desde que sale de la nave, así que durante el viaje pierde algo de peso. Por eso sale el mismo día que se prepara y llega a la mañana siguiente: el menor tiempo posible en camino.' ),
			array( '¿Y si no estoy cuando llega?', 'Lo mejor es dar una dirección donde haya alguien por la mañana. Si aun así no estás, la mensajería aplica sus reintentos: avísanos cuanto antes para seguir el envío, porque el hielo no espera.' ),
			array( '¿Puedo pedir una hora concreta?', 'El reparto es por la mañana y la hora exacta la marca la ruta de la mensajería. Si necesitas saber la hora, recógelo en Mataró: te la confirmamos antes.' ),
			array( '¿Hacéis envíos urgentes el mismo día?', 'No por mensajería. Si estás cerca de Mataró, puedes recogerlo el mismo día si pides antes de las 12:00. Te confirmamos la hora por teléfono o WhatsApp.' ),
		),
	),
);
