<?php
/* Comprar (ficha de producto) · castellano */
return array(
	'menu' => 'Comprar hielo seco',
	'seo'  => array(
		'titulo'      => 'Comprar hielo seco: 3, 10, 15 y 20 kg | DryIcePack',
		'descripcion' => 'Compra hielo seco desde 3 kg, en pellets de 3 mm o nuggets de 16 mm. Ves el total con envío antes de pagar. Pide antes de las 12:00 y llega mañana.',
	),
	'migas'   => array( 'Inicio', 'Comprar hielo seco' ),
	'titulo'  => 'Comprar hielo seco sin sorpresas en el envío',
	'sub'     => 'Pide antes de las 12:00 y mañana por la mañana lo tienes (de martes a sábado), o elige el día que quieras. El total ya lleva el envío.',
	'galeria' => array(
		'3mm'  => array( array( 'caja-3mm', 'Caja de hielo seco en pellets de 3 mm abierta, con vapor' ), array( 'cenital-3mm', 'Pellets de hielo seco de 3 mm vistos desde arriba' ), array( 'caja-3mm-lateral', 'Caja EPS con pellets de 3 mm y la tapa apoyada' ) ),
		'16mm' => array( array( 'caja-16mm-niebla', 'Caja de hielo seco en nuggets de 16 mm abierta, con vapor' ), array( 'cenital-16mm', 'Nuggets de hielo seco de 16 mm vistos desde arriba' ), array( 'cenital-caja-nuggets', 'Caja EPS abierta con nuggets de 16 mm, vista cenital' ) ),
	),
	'formato' => 'Formato',
	'formatos' => array(
		'3mm'  => array( 'Pellets de 3 mm', 'Enfría más rápido. Más niebla.' ),
		'16mm' => array( 'Nuggets de 16 mm', 'Dura más. Transporte y muestras.' ),
	),
	'kilos'     => 'Kilos por caja',
	'cajas'     => 'Cajas',
	'menos'     => 'Una caja menos',
	'mas'       => 'Una caja más',
	'cp'        => 'Tu código postal',
	'cp_ph'     => '08301',
	// Línea bajo el campo: ayuda y estado (una línea corta)
	'cp_ayuda'     => 'Para ver qué día te llega',
	'cp_buscando'  => 'Buscando tu zona…',
	'cp_correcto'  => 'Código postal correcto',
	'cp_fuera'     => 'Fuera de la península',
	'cp_medida'    => 'Envío a medida',
	'cp_no_valido' => 'Código postal no válido',
	'cp_corto'     => 'Faltan cifras: son 5',
	// Línea de entrega con el código postal (%1$s = "08301 · Barcelona", %2$s = fecha); "medida" termina en un enlace a WhatsApp; "fuera", no (no se envía)
	'llega_cp_ok'     => '%1$s — te llega el %2$s por la mañana',
	'llega_cp_sabado' => 'O el %1$s, según zona: +%2$s',
	'llega_cp_fuera'  => 'solo enviamos a la península: no a Baleares, Canarias, Ceuta ni Melilla.',
	'llega_cp_medida' => 'más de 150 kg fuera de la provincia de Barcelona: pídelo por',
	'llega_cp_error'  => 'El código postal %s no existe en España. Revisa las 5 cifras.',
	'llega'     => 'Lo tienes el %s por la mañana',
	'llega_hoy' => 'Si pides antes de las 12:00, lo tienes el %s por la mañana',
	'fuera'     => 'Solo enviamos a la península: no a Baleares, Canarias, Ceuta ni Melilla.',
	'precio'    => 'Hielo seco',
	'envio'     => 'Envío',
	'total'     => 'Total',
	'iva'       => 'IVA incluido',
	'boton'     => 'Hacer mi pedido',
	'recogida'  => 'O recógelo en Mataró: gratis de lunes a viernes, y pagas en efectivo al recogerlo.',
	'max'       => 'Hasta 250 kg por pedido. ¿Necesitas más? Escríbenos y te damos precio y día.',
	'medida'    => 'Más de 150 kg fuera de la provincia de Barcelona: ese envío se prepara a medida. Escríbenos por',
	'confianza' => array( 'Tarjeta, Apple Pay o Google Pay', 'Factura para empresas', 'Sin crear cuenta' ),
	'caja' => array(
		'titulo' => 'Así llega|<em>a tu puerta.</em>',
		'capas'  => array(
			array( 'Tapa de EPS', 'Encaja sin cerrar hermético: el gas sale poco a poco.' ),
			array( 'Hielo seco', 'Pellets de 3 mm o nuggets de 16 mm, a −78,5 °C.' ),
			array( 'Caja de EPS de 40 mm', 'Paredes gruesas de poliestireno: aíslan y hacen que el hielo dure más.' ),
		),
	),
	'comparar' => array(
		'titulo' => '¿3 mm o 16 mm?|<em>Arrastra</em> y compara.',
		'izq'    => array( '3 mm', 'Más superficie: enfría antes y hace más niebla. Para cócteles, efectos y procesos.' ),
		'der'    => array( '16 mm', 'Más masa por pieza: aguanta más horas en la caja. Para transporte, muestras y cadena de frío.' ),
		'rango'  => 'Deslizar para comparar 3 mm y 16 mm',
	),
	'cuanto' => array(
		'titulo' => '¿Cuánto|<em>necesito?</em>',
		'texto'  => 'Para niebla, estas cantidades sirven de referencia. ¿Es para transporte o muestras? Dinos cuántas horas y qué volumen, y te lo calculamos.',
		'casos'  => array(
			array( '3 kg', 'En casa', 'Un caldero, una ponchera con doble recipiente, una fiesta pequeña.' ),
			array( '10 kg', 'Fiesta grande', 'Niebla por el suelo en varias tandas durante la noche.' ),
			array( '15–20 kg', 'Bar o evento', 'Servicio largo, escenario o varias barras.' ),
		),
		'calcula' => 'Pregúntanos por WhatsApp',
		'seguridad' => 'Antes de usarlo, mira las seis reglas de seguridad',
	),
	'tarifa' => array(
		'titulo' => '¿Cuánto cuesta|<em>el envío?</em>',
		'texto'  => 'La tarifa de la mensajería, igual en toda la península. Se calcula con el peso del hielo más 1 kg por caja, y la ves antes de pagar.',
		'filas'  => array( array( 'Hasta 2 kg', 8.53 ), array( 'Hasta 5 kg', 10.32 ), array( 'Hasta 10 kg', 13.19 ), array( 'Cada kg de más', 1.12 ) ),
		'extra'  => array( array( 'Entrega en sábado (según zona)', 9.70 ), array( 'Recogida en Mataró, de lunes a viernes', 0 ) ),
		'nota'   => 'Precios con IVA incluido.',
		'gratis' => 'Gratis',
		'enlace' => 'Plazos de entrega, festivos y recogida',
	),
	'faq' => array(
		'titulo'   => 'Antes de pagar',
		'empresas' => 'Cuenta de empresa con factura mensual',
		'lista'    => array(
			array( '¿Cuándo llega?', 'Si pides antes de las 12:00 de lunes a jueves, sale ese mismo día y lo tienes al día siguiente por la mañana. Si pides el viernes, llega el sábado (según zona, con suplemento de 11,74 €) o el martes. No repartimos en domingo ni lunes. El día lo eliges al pagar.' ),
			array( '¿Puedo pedir para otro día?', 'Sí: al pagar eliges cualquier día de los próximos 90 con reparto en tu zona, de martes a sábado (el sábado, según zona y con suplemento). Pídelo para el día que lo vas a usar: el hielo seco se va sublimando con las horas.' ),
			array( '¿Cuánto dura el hielo en la caja?', 'Depende de la temperatura y de cuántas veces se abra la caja. Pídelo para el día que lo vas a usar y no la abras hasta entonces. Si lo necesitas para varios días, escríbenos y lo calculamos.' ),
			array( '¿Y si necesito factura?', 'Si eres particular y el pedido es de hasta 400 € (IVA incluido), te llega la factura simplificada por email desde info@dryicepack.es, sin pedirla. Si compras para una empresa o como autónomo, marca la casilla al pagar y pon la razón social y el NIF: recibes la factura completa. Si se te olvida, te enviamos un enlace para pedirla.' ),
			array( '¿Puedo devolverlo?', 'El hielo seco se sublima desde que sale, así que no tiene derecho de desistimiento. Si llega con cualquier problema, llámanos ese mismo día.' ),
			array( '¿Cómo lo guardo al recibirlo?', 'Con guantes térmicos, nunca con la mano. En su caja, con la tapa puesta pero sin precintar, en un sitio ventilado y fuera del alcance de niños y mascotas. Nunca en el congelador ni en un recipiente hermético: la presión puede reventarlo. No se come ni se bebe. Y si lo llevas en coche, en el maletero y ventilando.' ),
		),
	),
	'barra' => 'Total',
);
