<?php
/* Textos comuns en català: capçalera, peu, botons i avisos de seguretat. */
return array(
	'saltar'          => 'Anar al contingut',
	'inicio'          => 'Inici',
	'migas'           => 'Ets a',
	'menu_abrir'      => 'Obrir el menú',
	'menu_cerrar'     => 'Tancar el menú',
	'menu'            => array(
		'usos'      => 'Usos',
		'empresas'  => 'Empreses',
		'envios'    => 'Enviaments',
		'contacto'  => 'Contacte',
	),
	'usos'            => array(
		array( 'hosteleria', 'Hostaleria', 'Fum a la sala, còctels i fred a la barra', 'uso-hosteleria' ),
		array( 'transporte', 'Transport en fred', 'Congelat i refrigerat en ruta', 'uso-transporte' ),
		array( 'industria', 'Indústria', 'Refredar peces, assajos i volum', 'uso-industria' ),
		array( 'laboratorios', 'Laboratoris', 'Mostres a −78,5 °C', 'uso-laboratorio' ),
		array( 'eventos', 'Festes i esdeveniments', 'Boira baixa i efectes', 'uso-eventos' ),
	),
	'todos_usos'      => 'Tots els usos del gel sec',
	'comprar'         => 'Comprar gel sec',
	'comprar_corto'   => 'Comprar',
	'llamar'          => 'Trucar',
	'carrito'         => 'Cistella',
	'pago_seguro'     => 'Pagament segur',
	'finalizar'       => 'Finalitzar la compra',
	'no_encontrada'   => 'Pàgina no trobada',
	'error404'        => array(
		'titulo'  => 'Aquesta pàgina s\'ha <em>sublimat.</em>',
		'texto'   => 'No existeix o ha canviat d\'adreça. Això és el que se sol buscar:',
		'enlaces' => array( array( 'inicio', 'Inici' ), array( 'envios', 'Enviaments i terminis' ), array( 'empresas', 'Compte d\'empresa' ), array( 'contacto', 'Contacte' ) ),
	),
	'wa_mensaje'      => 'Hola, necessito gel sec. És per a:',
	'wa_etiqueta'     => 'WhatsApp',
	'wa_aria'         => 'Escriu-nos per WhatsApp al 686 980 471',
	'idioma'          => 'Idioma',
	// Peu
	'pie_frase'       => 'Gel sec que arriba <em>fred</em> i a l\'hora.',
	'pie_tienda'      => 'Gel sec',
	'pie_servicio'    => 'Servei',
	'pie_contacto'    => 'Parlem',
	'pie_enlaces'     => array(
		array( 'producto', 'Comprar' ),
		array( 'que-es', 'Què és el gel sec' ),
		array( 'seguridad', 'Seguretat i fitxa tècnica' ),
		array( 'aplicaciones', 'Usos per sector' ),
		array( 'guias', 'Guies' ),
	),
	'pie_servicios'   => array(
		array( 'empresas', 'Compte d\'empresa' ),
		array( 'envios', 'Enviaments i terminis' ),
		array( 'envios', 'Recollida a Mataró', 'recogida' ),
		array( 'zonas', 'Zones d\'entrega' ),
		array( 'contacto', 'Contacte' ),
	),
	'horario'         => 'De dilluns a divendres, 9:00–18:00',
	'legales'         => array(
		array( 'aviso-legal', 'Avís legal' ),
		array( 'privacidad', 'Privacitat' ),
		array( 'cookies', 'Galetes' ),
		array( 'condiciones', 'Condicions de venda' ),
	),
	'config_cookies'  => 'Configurar les galetes',
	'derechos'        => 'DryIcePack és una marca d\'INDUNOVA IMS S.L. · CIF B66800103',
	// Entrega (rellotge de l'hora límit)
	'corte_antes'     => 'Demana abans de les 12:00 i arriba el %s al matí',
	'corte_quedan'    => 'Falten %s per a l\'hora límit d\'avui',
	'corte_despues'   => 'Si demanes ara, arriba el %s al matí',
	'horas'           => 'h',
	'minutos'         => 'min',
	// Seguretat: els sis avisos (s'enllacen des de qualsevol pàgina que explica un ús)
	'seguridad'       => array(
		array( 'guante', 'Guants i pinces', 'Mai en contacte amb la pell: a −78,5 °C crema.' ),
		array( 'ventilar', 'Espai ventilat', 'El CO₂ desplaça l\'oxigen en llocs tancats.' ),
		array( 'hermetico', 'Res hermètic', 'En sublimar-se, la pressió augmenta i pot rebentar l\'envàs.' ),
		array( 'no-beber', 'No es menja ni es beu', 'Mai pèl·lets dins la copa: sempre doble recipient.' ),
		array( 'nino', 'Lluny de nens i mascotes', 'Guarda\'l a la seva caixa, fora del seu abast.' ),
		array( 'coche', 'Al maleter', 'I amb ventilació, mai a l\'habitacle tancat.' ),
	),
	'seguridad_mas'   => 'Seguretat completa i fitxa de dades',
	'faq'             => 'Preguntes freqüents',
	'volver_arriba'   => 'Tornar a dalt',
	'ver_mas'         => 'Veure\'n més',
	'kg'              => 'kg',
	'iva_incl'        => 'IVA inclòs',
	'con_envio'       => 'amb enviament',
	'por_kilo'        => '/kg',
	'form_privacidad' => 'He llegit la <a href="%s">política de privacitat</a>. Fem servir les teves dades només per respondre\'t.',
	'form_enviar'     => 'Enviar',
	'form_enviando'   => 'Enviant…',
	'form_ok'         => 'Rebut. Et responem en horari laboral, normalment el mateix dia.',
	'form_error'      => 'No s\'ha pogut enviar. Truca\'ns al 936 73 76 41.',
);
