<?php
/* Enviaments i terminis · català */
return array(
	'menu' => 'Enviaments i terminis',
	'seo'  => array(
		'titulo'      => 'Enviament de gel sec en 24 h a la península | DryIcePack',
		'descripcion' => 'Enviament de gel sec a tota la península: demana abans de les 12:00 i demà al matí el tens. Calcula aquí el cost de l\'enviament o recull-lo a Mataró.',
	),
	'migas'  => array( 'Inici', 'Enviaments i terminis' ),
	'hero'   => array(
		'titulo'   => 'Enviament de gel sec:|<em>demanes avui, demà el tens.</em>',
		'reloj'    => array( 'antes' => 'Temps per demanar avui', 'despues' => 'Per avui ja ha passat l\'hora límit' ),
		'llega'    => array( 'antes' => 'Si demanes ara, el tens el %s al matí.', 'despues' => 'Si demanes ara, el tens el %s al matí.' ),
		'texto'    => 'El que entra abans de les 12:00, de dilluns a divendres, surt aquell mateix dia i arriba l\'endemà al matí. El dia el tries en pagar.',
	),
	'semana' => array(
		'titulo' => 'Quin dia arriba?|<em>Depèn de quan demanis.</em>',
		'dias'   => array( 'Dilluns', 'Dimarts', 'Dimecres', 'Dijous', 'Divendres', 'Dissabte', 'Diumenge' ),
		'pides'  => 'Demanes abans de les 12:00',
		'llega'  => 'Arriba',
		'filas'  => array(
			array( 0, 1, '' ),
			array( 1, 2, '' ),
			array( 2, 3, '' ),
			array( 3, 4, '' ),
			array( 4, 5, 'Dissabte segons la zona, +11,74 €. Si no, dimarts.' ),
		),
		'finde'  => 'Les comandes de dissabte i diumenge, o de divendres després de les 12:00, surten dilluns i arriben dimarts.',
		'festivos' => 'Si és festiu a Mataró, a Catalunya o a tot Espanya, no surten comandes, i tampoc no s\'entrega en un festiu de la missatgeria a la teva zona. No cal que ho miris: en pagar només apareixen els dies possibles.',
	),
	'tarifa' => array(
		'titulo' => 'Quant costa l\'enviament?|<em>Mou els quilos i ho veus.</em>',
		'kg'     => 'Quilos de gel',
		'mas'       => 'Més de 150 kg',
		'mas_cifra' => '+150',
		'cajas_titulo' => 'Així te l\'enviem',
		'caja_una'     => '%1$s caixa de %2$s kg',
		'caja_varias'  => '%1$s caixes de %2$s kg',
		'caja_resto'   => ' + %1$s de %2$s kg',
		'pedir'     => array( 'boton' => 'Demanar %s kg', 'formato' => 'Format', 'f3mm' => 'Pèl·lets 3 mm', 'f16mm' => 'Nuggets 16 mm', 'nota' => 'Te\'l deixem a la cistella tal qual i passes al pagament.' ),
		'coste_iva' => 'Enviament, IVA inclòs',
		'filas'     => array(
			'hielo'    => 'Gel',
			'embalaje' => 'Caixes (1 kg cadascuna)',
			'peso'     => 'Pes facturable',
			'redondeo' => 'arrodonit a l\'alça',
			'sin_iva'  => 'Enviament sense IVA',
			'iva'      => 'IVA (%s)',
		),
		'tramo'  => 'tarifa fins a %s kg',
		'extra'  => '%1$s fins a 10 kg + %2$s kg × %3$s',
		'nota'   => 'Comptem caixes de 20 kg i la resta en el pack que toqui (3, 10 o 15 kg), com si ho demanessis a la botiga. La missatgeria cobra el gel més 1 kg per caixa, arrodonit a l\'alça: el mateix càlcul que es fa en pagar.',
		'medida' => array(
			'cajas'  => 'Caixes a mida de la comanda',
			'titulo' => 'Et preparem preu i dia.',
			'texto'  => 'A la província de Barcelona t\'ho portem a les teves instal·lacions; fora, l\'enviament va a mida.',
			'boton'  => 'Demanar preu',
			'wa'     => 'Hola, necessito més de 150 kg de gel sec. Em prepareu preu i dia?',
			'tel'    => 'o truca al',
		),
	),
	'recogida' => array(
		'titulo' => 'Recollida a Mataró,|<em>sense esperar la missatgeria.</em>',
		'lista'  => array(
			array( 'On', 'Camí Ca La Madrona 19 D, 08304 Mataró (Barcelona). És la nostra nau, no una oficina de la missatgeria.' ),
			array( 'Quan', 'De dilluns a dissabte, també festius. Tria el dia en pagar i et confirmem l\'hora per telèfon o WhatsApp. El dissabte té un suplement d\'11,74 € (IVA inclòs).' ),
			array( 'Quant', 'Gratis de dilluns a divendres. Només pagues el gel, en efectiu quan el reculls.' ),
			array( 'Com portar-lo', 'Mai a l\'habitacle: al maleter i ventilant.' ),
		),
		'alt'    => 'Operari amb un cassó de pèl·lets de gel sec al magatzem',
		'como'   => 'Com arribar-hi',
	),
	'cobertura' => array(
		'titulo' => 'Arriba a la meva zona?',
		'si'     => array( 'titulo' => 'Sí, l\'endemà al matí', 'texto' => 'Tota l\'Espanya peninsular: de Girona a Huelva i de la Corunya a Múrcia.' ),
		'no'     => array( 'titulo' => 'Fora de la península, no', 'texto' => 'Només enviem a la península: no a les Balears, les Canàries, Ceuta ni Melilla, ni fora d\'Espanya.' ),
		'zonas'  => 'Veure les zones d\'entrega a prop de Barcelona',
	),
	'faq' => array(
		'titulo' => 'Dubtes sobre l\'enviament',
		'lista'  => array(
			array( 'Com va embalat?', 'En caixa d\'EPS amb parets de 40 mm, tancada amb la tapa però no hermètica, perquè el CO₂ pugui sortir durant el viatge.' ),
			array( 'Arriba el mateix pes que demano?', 'El gel sec se sublima des que surt de la nau, així que durant el viatge perd una mica de pes. Per això surt el mateix dia que es prepara i arriba l\'endemà al matí: el mínim temps possible en camí.' ),
			array( 'I si no hi soc quan arriba?', 'El millor és donar una adreça on hi hagi algú al matí. Si així i tot no hi ets, la missatgeria ho torna a intentar: avisa\'ns com més aviat millor per seguir l\'enviament, perquè el gel no espera.' ),
			array( 'Puc demanar una hora concreta?', 'El repartiment és al matí i l\'hora exacta la marca la ruta de la missatgeria. Si necessites saber l\'hora, recull-lo a Mataró: te la confirmem abans.' ),
			array( 'Feu enviaments urgents el mateix dia?', 'No per missatgeria. Si ets a prop de Mataró, el pots recollir el mateix dia si demanes abans de les 12:00. Et confirmem l\'hora per telèfon o WhatsApp.' ),
		),
	),
);
