<?php
/* Condicions de venda · català. Actualitzen el PDF de desembre de 2025 a com funciona avui la botiga. */
return array(
	'seo'        => array(
		'titulo'      => 'Condicions de venda del gel sec | DryIcePack',
		'descripcion' => 'Condicions de venda: preus, pagament, factura, terminis d\'entrega, recollida a Mataró, dissabte, incidències i per què el gel sec no té desistiment.',
	),
	'titulo'     => 'Condicions de venda',
	'actualizado'=> 'Darrera actualització: 30 de setembre de 2026',
	'secciones'  => array(
		array( 'Qui ven', '<p>INDUNOVA IMS S.L. (DryIcePack) · NIF B66800103 · Ronda Alfonso X El Sabio, 10, 2º 1ª, 08301 Mataró (Barcelona) · info@dryicepack.es · 936 73 76 41.</p><p>Aquestes condicions s\'apliquen a les compres a www.dryicepack.es, tant de consumidors com d\'empreses. En confirmar una comanda s\'accepten les condicions vigents en aquell moment.</p>' ),
		array( 'El producte', '<p>Gel sec (diòxid de carboni sòlid, UN 1845) en pèl·lets de 3 mm i nuggets de 16 mm, en caixa d\'EPS amb parets de 40 mm. És a −78,5 °C i se sublima de manera natural des que es prepara: durant el transport perd una mica de pes, sense que això es consideri un defecte.</p><p>És un producte que s\'ha de manipular amb guants, en llocs ventilats i mai en envasos hermètics. Les normes d\'ús són a la pàgina de seguretat i a la fitxa de dades de seguretat.</p>' ),
		array( 'On venem', '<p>A la botiga en línia, a l\'Espanya peninsular. Per a les Illes Balears, Canàries, Ceuta, Melilla o altres destinacions, s\'estudia cada cas per correu electrònic.</p>' ),
		array( 'Preus', '<p>Els preus són en euros. Abans de pagar es mostra el preu final amb IVA i el cost de l\'enviament, que es calcula per pes (gel més 1 kg per caixa). L\'entrega en dissabte, quan la zona ho permet, té un suplement d\'11,74 € amb IVA. La recollida a la nau de Mataró és gratuïta.</p>' ),
		array( 'Com es compra', '<p>Es pot comprar sense crear cap compte. El client tria format, quilos, forma d\'entrega i dia, i rep un correu electrònic de confirmació. El màxim per comanda en línia és de 250 kg; per a quantitats més grans cal demanar pressupost.</p><p>Els comptes d\'empresa s\'obren amb una sol·licitud prèvia i poden tenir preu propi i pagament amb factura mensual, segons el que s\'acordi per escrit.</p>' ),
		array( 'Pagament', '<ul><li>Amb enviament: targeta, Apple Pay o Google Pay, mitjançant una passarel·la de pagament segura.</li><li>Amb recollida a Mataró: en efectiu en el moment de recollir.</li><li>Comptes d\'empresa: factura mensual per transferència o domiciliació, segons el que s\'hagi acordat.</li></ul>' ),
		array( 'Factura', '<p>Cada venda té la seva factura. Als particulars se\'ls emet factura simplificada. Les empreses i els autònoms reben factura completa si indiquen la raó social i el NIF/CIF en comprar; en comandes de més de 400 € (IVA inclòs) aquestes dades són obligatòries. Si es va comprar sense indicar-les, es pot demanar la factura completa amb l\'enllaç que enviem per correu electrònic.</p>' ),
		array( 'Terminis d\'entrega', '<ul><li>Les comandes fetes abans de les 12:00 (hora peninsular) d\'un dia laborable, de dilluns a divendres, surten aquell dia.</li><li>L\'entrega és l\'endemà al matí, de dimarts a divendres. No s\'entrega ni en diumenge ni en dilluns.</li><li>El dissabte s\'entrega segons el codi postal, amb suplement.</li><li>Els dies festius no surten comandes. En el pagament només es poden triar dies disponibles.</li></ul><p>Els terminis depenen de l\'empresa de missatgeria. Si el destinatari no hi és o l\'adreça és incorrecta, s\'apliquen els nous intents d\'entrega de la missatgeria; atesa la naturalesa del producte, avisi com més aviat millor.</p>' ),
		array( 'Recollida a Mataró', '<p>Al Camí Ca La Madrona 19 D, 08304 Mataró, de dilluns a dissabte (el dissabte amb un suplement de 9,70 € + IVA), el dia triat en fer la comanda i a l\'hora que confirmem amb el client. Si la comanda no es recull el dia acordat, el gel se sublima i no se\'n pot reemborsar l\'import.</p>' ),
		array( 'Desistiment', '<p>El gel sec no té dret de desistiment: és un bé que es pot deteriorar o caducar amb rapidesa (article 103.d del Text refós de la Llei general per a la defensa dels consumidors i usuaris).</p>' ),
		array( 'Incidències', '<p>Si la comanda arriba amb un problema (caixa danyada, quantitat clarament inferior a l\'esperable o error en el format), escrigui a info@dryicepack.es o truqui al 936 73 76 41 el mateix dia de l\'entrega, amb fotos si és possible. Si la incidència ens és imputable, reposarem la comanda o en retornarem l\'import.</p>' ),
		array( 'Responsabilitat', '<p>El client es responsabilitza d\'utilitzar el gel sec d\'acord amb les normes de seguretat. INDUNOVA IMS S.L. no respon dels danys causats per un ús indegut.</p>' ),
		array( 'Atenció al client i reclamacions', '<p>info@dryicepack.es · 936 73 76 41, de dilluns a divendres de 9:00 a 18:00. INDUNOVA IMS S.L. disposa de fulls oficials de reclamació. La documentació contractual està disponible en castellà i en català.</p>' ),
		array( 'Llei aplicable', '<p>Aquestes condicions es regeixen per la legislació espanyola. Si el client és consumidor, són competents els jutjats del seu domicili.</p>' ),
	),
);
