<?php
/* Comprar (fitxa de producte) · català */
return array(
	'menu' => 'Comprar gel sec',
	'seo'  => array(
		'titulo'      => 'Comprar gel sec: 3, 10, 15 i 20 kg | DryIcePack',
		'descripcion' => 'Compra gel sec des de 3 kg, en pèl·lets de 3 mm o nuggets de 16 mm. Veus el total amb enviament abans de pagar. Demana abans de les 12:00 i arriba demà.',
	),
	'migas'   => array( 'Inici', 'Comprar gel sec' ),
	'titulo'  => 'Comprar gel sec sense sorpreses amb l\'enviament',
	'sub'     => 'Demana abans de les 12:00 i demà al matí el tens (de dimarts a dissabte), o tria el dia que vulguis. El total ja inclou l\'enviament.',
	'galeria' => array(
		'3mm'  => array( array( 'caja-3mm', 'Caixa de gel sec en pèl·lets de 3 mm oberta, amb vapor' ), array( 'cenital-3mm', 'Pèl·lets de gel sec de 3 mm vistos des de dalt' ), array( 'caja-3mm-lateral', 'Caixa EPS amb pèl·lets de 3 mm i la tapa recolzada' ) ),
		'16mm' => array( array( 'caja-16mm-niebla', 'Caixa de gel sec en nuggets de 16 mm oberta, amb vapor' ), array( 'cenital-16mm', 'Nuggets de gel sec de 16 mm vistos des de dalt' ), array( 'cenital-caja-nuggets', 'Caixa EPS oberta amb nuggets de 16 mm, vista zenital' ) ),
	),
	'formato' => 'Format',
	'formatos' => array(
		'3mm'  => array( 'Pèl·lets de 3 mm', 'Refreda més de pressa. Més boira.' ),
		'16mm' => array( 'Nuggets de 16 mm', 'Dura més. Transport i mostres.' ),
	),
	'kilos'     => 'Quilos per caixa',
	'cajas'     => 'Caixes',
	'menos'     => 'Una caixa menys',
	'mas'       => 'Una caixa més',
	'cp'        => 'El teu codi postal',
	'cp_ph'     => '08301',
	// Línia sota el camp: ajuda i estat (una línia curta)
	'cp_ayuda'     => 'Per veure quin dia t\'arriba',
	'cp_buscando'  => 'Buscant la teva zona…',
	'cp_correcto'  => 'Codi postal correcte',
	'cp_fuera'     => 'Fora de la península',
	'cp_medida'    => 'Enviament a mida',
	'cp_no_valido' => 'Codi postal no vàlid',
	'cp_corto'     => 'Falten xifres: són 5',
	// Línia d'entrega amb el codi postal (%1$s = "08301 · Barcelona", %2$s = data); "medida" acaba amb un enllaç a WhatsApp; "fuera", no (no s'hi envia)
	'llega_cp_ok'     => '%1$s — t\'arriba el %2$s al matí',
	'llega_cp_sabado' => 'O el %1$s, segons la zona: +%2$s',
	'llega_cp_fuera'  => 'només enviem a la península: no a les Balears, les Canàries, Ceuta ni Melilla.',
	'llega_cp_medida' => 'més de 150 kg fora de la província de Barcelona: demana-ho per',
	'llega_cp_error'  => 'El codi postal %s no existeix a Espanya. Revisa les 5 xifres.',
	'llega'     => 'El tens el %s al matí',
	'llega_hoy' => 'Si demanes abans de les 12:00, el tens el %s al matí',
	'fuera'     => 'Només enviem a la península: no a les Balears, les Canàries, Ceuta ni Melilla.',
	'precio'    => 'Gel sec',
	'envio'     => 'Enviament',
	'total'     => 'Total',
	'iva'       => 'IVA inclòs',
	'boton'     => 'Fer la comanda',
	'recogida'  => 'O recull-lo a Mataró: gratis de dilluns a divendres, i pagues en efectiu quan el reculls.',
	'max'       => 'Fins a 250 kg per comanda. En necessites més? Escriu-nos i et donem preu i dia.',
	'medida'    => 'Més de 150 kg fora de la província de Barcelona: aquest enviament es prepara a mida. Escriu-nos per',
	'confianza' => array( 'Targeta, Apple Pay o Google Pay', 'Factura per a empreses', 'Sense crear cap compte' ),
	'caja' => array(
		'titulo' => 'Així arriba|<em>a la teva porta.</em>',
		'capas'  => array(
			array( 'Tapa d\'EPS', 'Encaixa sense tancar hermèticament: el gas surt a poc a poc.' ),
			array( 'Gel sec', 'Pèl·lets de 3 mm o nuggets de 16 mm, a −78,5 °C.' ),
			array( 'Caixa d\'EPS de 40 mm', 'Parets gruixudes de poliestirè: aïllen i fan que el gel duri més.' ),
		),
	),
	'comparar' => array(
		'titulo' => '3 mm o 16 mm?|<em>Arrossega</em> i compara.',
		'izq'    => array( '3 mm', 'Més superfície: refreda abans i fa més boira. Per a còctels, efectes i processos.' ),
		'der'    => array( '16 mm', 'Més massa per peça: aguanta més hores a la caixa. Per a transport, mostres i cadena de fred.' ),
		'rango'  => 'Llisca per comparar 3 mm i 16 mm',
	),
	'cuanto' => array(
		'titulo' => 'Quant|<em>en necessito?</em>',
		'texto'  => 'Per fer boira, aquestes quantitats et serviran de referència. És per a transport o mostres? Digues-nos quantes hores i quin volum, i t\'ho calculem.',
		'casos'  => array(
			array( '3 kg', 'A casa', 'Un calder, una ponxera amb doble recipient, una festa petita.' ),
			array( '10 kg', 'Festa gran', 'Boira arran de terra en diverses tandes durant la nit.' ),
			array( '15–20 kg', 'Bar o esdeveniment', 'Servei llarg, escenari o diverses barres.' ),
		),
		'calcula' => 'Pregunta\'ns per WhatsApp',
		'seguridad' => 'Abans de fer-lo servir, mira les sis normes de seguretat',
	),
	'tarifa' => array(
		'titulo' => 'Quant costa|<em>l\'enviament?</em>',
		'texto'  => 'La tarifa de la missatgeria, igual a tota la península. Es calcula amb el pes del gel més 1 kg per caixa, i la veus abans de pagar.',
		'filas'  => array( array( 'Fins a 2 kg', 8.53 ), array( 'Fins a 5 kg', 10.32 ), array( 'Fins a 10 kg', 13.19 ), array( 'Cada kg de més', 1.12 ) ),
		'extra'  => array( array( 'Entrega en dissabte (segons la zona)', 9.70 ), array( 'Recollida a Mataró, de dilluns a divendres', 0 ) ),
		'nota'   => 'Preus amb IVA inclòs.',
		'gratis' => 'Gratis',
		'enlace' => 'Terminis d\'entrega, festius i recollida',
	),
	'faq' => array(
		'titulo'   => 'Abans de pagar',
		'empresas' => 'Compte d\'empresa amb factura mensual',
		'lista'    => array(
			array( 'Quan arriba?', 'Si demanes abans de les 12:00 de dilluns a dijous, surt aquell mateix dia i el tens l\'endemà al matí. Si demanes divendres, arriba dissabte (segons la zona, amb un suplement d\'11,74 €) o dimarts. No repartim ni diumenge ni dilluns. El dia el tries en pagar.' ),
			array( 'Puc demanar per a un altre dia?', 'Sí: en pagar tries qualsevol dia dels pròxims 90 amb repartiment a la teva zona, de dimarts a dissabte (el dissabte, segons la zona i amb suplement). Demana\'l per al dia que el faràs servir: el gel sec es va sublimant amb les hores.' ),
			array( 'Quant dura el gel a la caixa?', 'Depèn de la temperatura i de quantes vegades s\'obri la caixa. Demana\'l per al dia que el faràs servir i no l\'obris fins aleshores. Si el necessites per a diversos dies, escriu-nos i ho calculem.' ),
			array( 'I si necessito factura?', 'Si ets particular i la comanda és de fins a 400 € (IVA inclòs), t\'arriba la factura simplificada per correu electrònic des d\'info@dryicepack.es, sense demanar-la. Si compres per a una empresa o com a autònom, marca la casella en pagar i posa-hi la raó social i el NIF: reps la factura completa. Si te n\'oblides, t\'enviem un enllaç per demanar-la.' ),
			array( 'El puc tornar?', 'El gel sec se sublima des que surt, així que no té dret de desistiment. Si arriba amb qualsevol problema, truca\'ns aquell mateix dia.' ),
			array( 'Com el guardo quan el rebo?', 'Amb guants tèrmics, mai amb la mà. A la seva caixa, amb la tapa posada però sense precintar, en un lloc ventilat i fora de l\'abast de nens i mascotes. Mai al congelador ni en un recipient hermètic: la pressió el pot rebentar. No es menja ni es beu. I si el portes en cotxe, al maleter i ventilant.' ),
		),
	),
	'barra' => 'Total',
);
